<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales v4.x.x
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<?php
$column = $block->getColumn();
?>

<label class="<?= isset($column['class']) ? $column['class'] : 'label-text'?>"
    <?= isset($column['style']) ? 'style=' . $column['style'] : '' ?>><%- <?= $block->getColumnName() ?> %>
</label>
<input type="hidden"
       name="<?= $block->getInputName() ?>"
       value="<%- <?= $block->getColumnName() ?> %>"
       data-form-part="prprivatesale_event_form">
