<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Review\Block\Customer\ListCustomer $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

/** @var \Magento\Review\Helper\Data $reviewHelper */
$reviewHelper = $block->getData('reviewHelper');
?>
<?php if ($block->getReviews() && count($block->getReviews())): ?>
    <div class="reviews">
        <ul class="reviews-list" id="my-reviews-table">
            <?php foreach ($block->getReviews() as $review): ?>
            <li class="review-item">
                <div class="review-item-inner">
                    <div class="review-username">
                        <span class="username">
                            <?= $block->getCustomer()->getFirstname() ?>
                            <?= $block->getCustomer()->getMiddlename() ?>
                            <?= $block->getCustomer()->getLastname() ?>
                        </span>
                        <div class="review-rating mobile-hide">
                            <?php if ($review->getSum()): ?>
                                <div class="rating-summary">
                                    <span class="label"><span><?= $escaper->escapeHtml(__('Rating')) ?>:</span></span>
                                    <div class="rating-result"
                                         id="rating-result_<?= /* @noEscape */ $block->escapeHtml($review->getId()) ?>"
                                         title="<?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%">
                                    <span class="rating_<?= $escaper->escapeUrl($review->getReviewId())?>">
                                        <span>
                                            <?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%
                                        </span>
                                    </span>
                                    </div>
                                </div>
                                <?= /* @noEscape */
                                $secureRenderer->renderStyleAsTag(
                                    "width:" . /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) . "%;",
                                    'div.rating-summary div.rating-result>span.rating_' .
                                    $escaper->escapeUrl($review->getReviewId())
                                ) ?>
                            <?php endif; ?>
                            <span class="review-date">
                                <time class="review-details-value" itemprop="datePublished"
                                      datetime="<?= $escaper->escapeHtmlAttr(
                                          date("M j, Y", strtotime($review->getCreatedAt()))
                                      ) ?>">
                                    <?= $escaper->escapeHtmlAttr(
                                        date("M j, Y", strtotime($review->getCreatedAt()))
                                    )?>
                                </time>
                            </span>
                        </div>
                    </div>
                    <div class="review-product-name">
                        <a href="<?= $escaper->escapeUrl($block->getProductUrl($review)) ?>">
                            <?= $escaper->escapeHtml($review->getName()) ?>
                        </a>
                    </div>
                    <div class="review-rating desktop-hide">
                        <?php if ($review->getSum()): ?>
                            <div class="rating-summary">
                                <span class="label"><span><?= $escaper->escapeHtml(__('Rating')) ?>:</span></span>
                                <div class="rating-result"
                                     id="rating-result_<?= /* @noEscape */ $block->escapeHtml($review->getId()) ?>"
                                     title="<?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%">
                                <span class="rating_<?= $escaper->escapeUrl($review->getReviewId())?>">
                                    <span>
                                        <?= /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) ?>%
                                    </span>
                                </span>
                                </div>
                            </div>
                            <?= /* @noEscape */
                            $secureRenderer->renderStyleAsTag(
                                "width:" . /* @noEscape */ ((int)$review->getSum() / (int)$review->getCount()) . "%;",
                                'div.rating-summary div.rating-result>span.rating_' .
                                $escaper->escapeUrl($review->getReviewId())
                            ) ?>
                        <?php endif; ?>
                        <span class="review-date">
                            <time class="review-details-value" itemprop="datePublished"
                                  datetime="<?= $escaper->escapeHtmlAttr(
                                      date("M j, Y", strtotime($review->getCreatedAt()))
                                  ) ?>">
                                    <?= $escaper->escapeHtmlAttr(
                                        date("M j, Y", strtotime($review->getCreatedAt()))
                                    )?>
                                </time>
                        </span>
                    </div>
                    <div class="review-description">
                        <?= /* @noEscape */ nl2br($escaper->escapeHtml($review->getDetail())) ?>
                    </div>
                </div>
            </li>
            <?php endforeach; ?>
        </ul>
    </div>
    <?php if ($block->getToolbarHtml()): ?>
        <div class="toolbar products-reviews-toolbar bottom">
            <?= $block->getToolbarHtml() ?>
        </div>
    <?php endif; ?>
<?php else: ?>
    <div class="message info empty"><span><?= $escaper->escapeHtml(__('You have submitted no reviews.')) ?></span></div>
<?php endif; ?>
