<script>
    require([
        "jquery",
        "Magento_Ui/js/modal/modal",
        'mage/backend/notification',
        "prototype"
    ], function(jQuery, modal, notification) {

//<![CDATA[
        Window.keepMultiModalWindow = true;
        var adminApiLogView = {
            overlayShowEffectOptions : null,
            overlayHideEffectOptions : null,
            modal: null,
            activityId: 0,
            open : function(editorUrl, elementId) {
                if (editorUrl && elementId) {
                    jQuery.ajax({
                        url: editorUrl,
                        data: {
                            id: elementId
                        },
                        showLoader: true,
                        dataType: 'html',
                        success: function(data, textStatus, transport) {
                            this.openDialogWindow(data, elementId);
                        }.bind(this)
                    });
                }
            },
            openDialogWindow : function(data, elementId) {
                var self = this;
                this.activityId = elementId;
                if (this.modal) {
                    this.modal.html(jQuery(data).html());
                } else {
                    this.modal = jQuery(data).modal({
                        title: '<?= /* @escapeNotVerified */ __('Api Log'); ?>',
                        modalClass: 'magento',
                        type: 'slide',
                        firedElementId: elementId,
                        buttons: [
                            {
                                text: jQuery.mage.__('Format Json'),
                                class: 'action- scalable pretty',
                                click: function () {
                                    self.prettyData(this);
                                }
                            },
                            {
                            text: jQuery.mage.__('Back'),
                            class: 'action- scalable back',
                            click: function () {
                                self.closeDialogWindow(this);
                            }
                        }],
                        close: function () {
                            self.closeDialogWindow(this);
                        }
                    });
                }
                this.modal.modal('openModal');
                this.autoResize();
            },
            prettyData: function() {
                let elemContent = jQuery('#api_content');
                let elemContentPretty = jQuery('#api_content_pretty');
                let elemException = jQuery('#api_exception');
                let elemExceptionPretty = jQuery('#api_exception_pretty');
                if(elemContent.css("display") !== "none"){
                    // data content
                    if(elemContent.text()) {
                        let prettyContent = JSON.stringify(JSON.parse(elemContent.text()), undefined, 2);
                        elemContentPretty.text(prettyContent);
                        elemContentPretty.show();
                        elemContent.hide();
                    }
                    // data exception
                    if(elemException.text()) {
                        let prettyException = JSON.stringify(JSON.parse(elemException.text()), undefined, 2);
                        elemExceptionPretty.text(prettyException);
                        elemExceptionPretty.show();
                        elemException.hide();
                    }
                }else{
                    elemContentPretty.hide();
                    elemContent.show();
                    elemExceptionPretty.hide();
                    elemException.show();
                }
            },
            closeDialogWindow : function(dialogWindow) {

                jQuery('body').trigger('processStop');
                dialogWindow.closeModal();
                Windows.overlayShowEffectOptions = this.overlayShowEffectOptions;
                Windows.overlayHideEffectOptions = this.overlayHideEffectOptions;
            },
            error: function (message) {
                jQuery('body').notification('clear')
                    .notification('add', {
                        error: true,
                        message: jQuery.mage.__(message),
                        insertMethod: function (message) {
                            var $wrapper = jQuery('<div>').html(message);
                            jQuery('.page-main-actions').after($wrapper);
                        }
                    });
            },
            autoResize: function () {
                jQuery.each(jQuery('textarea.value-container'), function() {
                    var offset = this.offsetHeight - this.clientHeight;
                    var resizeTextarea = function(el) {
                        console.log('You clicked me!!');
                        jQuery(el).css('height', 'auto').css('height', el.scrollHeight + offset);
                    };
                    jQuery(this).unbind().on('click', function() { resizeTextarea(this); }).trigger('click');
                });
            }
        };

        window.adminApiLogView = adminApiLogView;
//]]>

    });
</script>
