<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Address\Book $block */
?>
<div class="block block-addresses-title mobile-hide">
    <div class="block-title">
        <strong><?= __('My address') ?></strong>
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('New Address')) ?></span></button>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
<div class="block block-addresses-default">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Default Addresses')) ?></strong></div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getDefaultShipping()) : ?>
            <div class="box box-address-shipping">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Delivery Address')) ?></span>
                </strong>
                <div class="box-content">
                    <address>
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <span><?= $block->escapeHtml(__('Edit Address')) ?></span>
                    </a>
                </div>
            </div>
        <?php else : ?>
            <div class="box box-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Delivery Address')) ?></span></strong>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>

        <?php if ($_pAddsses = $block->getDefaultBilling()) : ?>
            <div class="box box-address-billing">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Billing Address')) ?></span>
                </strong>
                <div class="box-content">
                    <address>
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                    </address>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <span><?= $block->escapeHtml(__('Edit Address')) ?></span>
                    </a>
                </div>
            </div>
        <?php else : ?>
            <div class="box box-billing-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Billing Address')) ?></span></strong>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
