<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<div class="maintenance-wrapper">
    <img class="logo" src="images/goldilocks-logo.png" alt="goldilocks-logo">
    <img class="maintenance-face" src="images/maintenance-face.png" alt="goldilocks-logo">
    <h1>We'll be back soon!</h1>
    <p>
        <span>Our website is under maintenance.</span>
        <span> Please come back later.</span>
    </p>
    <div class="maintenance-bottom"></div>
</div>
