<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var \Magenest\AdvancedLogin\Block\Form\CustomAttribute\Attributes $block */
?>
<?php if ($block->getActiveTelephone()): ?>
    <div class="field field-telephone required">
        <label class="label" for="telephone"><span><?= $block->escapeHtml(__('Phone')) ?></span></label>
        <div class="control">
            <input type="text"
                   id="telephone"
                   name="telephone"
                   value="<?= $block->getTelephone() ?>"
                   class="input-text"
                   <?= $block->isInCustomerUpdatePage() ? "readonly" : "" ?>
                   data-validate="{required: true, 'phone-validate': true}"
            >
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "*": {
           "validateMethod": {}
       }
    }
</script>
