<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>

<script type="text/javascript">
    require([
        'jquery',
        'domReady!'
    ], function ($) {
        'use strict';

        var interval,
            popupType = '<?= $block->typeOfPopupForm() ?>';

        interval = setInterval(function () {
            if (typeof window.plumrocket !== 'undefined'
                && typeof window.plumrocket.popupLoginControl !== 'undefined'
            ) {
                if (popupType === '1') {
                    window.plumrocket.popupLoginControl.openLoginForm();
                } else if (popupType === '2') {
                    window.plumrocket.popupLoginControl.openRegistrationForm();
                }
                clearInterval(interval);
            }
        }, 500);
    });
</script>
