<?php

namespace Magenest\AbandonedCart\Block\Adminhtml\Rule\Edit\Tab;

class GoogleAnalytics extends \Magento\Backend\Block\Widget\Form\Generic implements \Magento\Backend\Block\Widget\Tab\TabInterface
{

    /**
     * GoogleAnalytics constructor.
     *
     * @param \Magento\Backend\Block\Template\Context $context
     * @param \Magento\Framework\Registry $registry
     * @param \Magento\Framework\Data\FormFactory $formFactory
     * @param array $data
     */
    public function __construct(
        \Magento\Backend\Block\Template\Context $context,
        \Magento\Framework\Registry $registry,
        \Magento\Framework\Data\FormFactory $formFactory,
        array $data = []
    ) {
        parent::__construct($context, $registry, $formFactory, $data);
    }

    public function _prepareForm()
    {
        $ruleModel = $this->_coreRegistry->registry('abandonedcart_rule');
        /** @var \Magento\Framework\Data\Form $form */
        $form = $this->_formFactory->create();
        $form->setHtmlIdPrefix('rule_');
        $fieldset = $form->addFieldset(
            'setting_fieldset',
            [
                'legend' => __('Google Analytics'),
                'class'  => 'fieldset-wide'
            ]
        );
        $fieldset->addField(
            'ga_source',
            'text',
            [
                'name'  => 'ga_source',
                'label' => __('Campaign Source'),
                'title' => __('Campaign Source'),
                'note'  => __('Google analytics Source'),
            ]
        );

        $fieldset->addField(
            'ga_medium',
            'text',
            [
                'name'  => 'ga_medium',
                'label' => __('Campaign Medium'),
                'title' => __('Campaign Medium'),
                'note'  => __('Google analytics medium'),
            ]
        );

        $fieldset->addField(
            'ga_name',
            'text',
            [
                'name'  => 'ga_name',
                'label' => __('Campaign Name'),
                'title' => __('Campaign Name'),
                'note'  => __('Google analytics name'),
            ]
        );

        $fieldset->addField(
            'ga_term',
            'text',
            [
                'name'  => 'ga_term',
                'label' => __('Campaign Term'),
                'title' => __('Campaign Term'),
                'note'  => __('Google analytics name'),
            ]
        );

        $fieldset->addField(
            'ga_content',
            'text',
            [
                'name'  => 'ga_content',
                'label' => __('Campaign Content'),
                'title' => __('Campaign Content'),
                'note'  => __('Google analytics name'),
            ]
        );
        $this->setForm($form);
        if ($this->getRequest()->getParam('id')) {
            $editData = $ruleModel->getData();
            if ($editData['stores_view']) {
                $editData['stores_view'] = json_decode($editData['stores_view'], true);
            }

            if ($editData['customer_group']) {
                $editData['customer_group'] = json_decode($editData['customer_group'], true);
            }
            $editData['id'] = $this->getRequest()->getParam('id');
            $form->setValues($editData);
        }

        return parent::_prepareForm(); // TODO: Change the autogenerated stub
    }

    public function getTabLabel()
    {
        return __('Google Analytics');
    }

    public function getTabTitle()
    {
        return __('Google Analytics');
    }

    public function canShowTab()
    {
        return true;
    }

    public function isHidden()
    {
        return false;
    }
}
