<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/** @var \Plumrocket\PrivateSale\Block\Event\Widget\AbstractWidget $block */
?>

<?php if (! empty($block->getEvents())) : ?>
    <div class="shops-holder">
        <div class="pps-row">
            <?php if ($block->getBlockTitle()): ?>
                <header>
                    <h3><?= $block->getBlockTitle() ?></h3>
                </header>
            <?php endif; ?>
            <section>
                <?php foreach ($block->getEvents() as $event) : ?>
                    <?= $block->getEventHtml($event) ?>
                <?php endforeach; ?>
            </section>
        </div>
    </div>
<?php endif; ?>
