<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */
?>
<?php /** @var \Plumrocket\PrivateSale\Block\Event\Widget\Active $block */ ?>
<?php if (! $block->getGroupedEvents()): ?>
    <?php return ?>
<?php endif?>
<?php $showTitle = true; ?>

<?php foreach ($block->getGroupedEvents() as $group) : ?>
    <?php if (! empty($group['events'])) : ?>
        <div class="shops-holder">
            <div class="pps-row">
                <?php if ($showTitle && $block->getBlockTitle()): ?>
                    <header>
                        <h2><?= $block->getBlockTitle() ?></h2>
                        <?php $showTitle = false; ?>
                    </header>
                <?php endif; ?>
                <header>
                    <h3><?= $group['name'] ?></h3>
                </header>
                <section>
                    <?php foreach ($group['events'] as $event) : ?>
                        <?= $block->getEventHtml($event) ?>
                    <?php endforeach; ?>
                </section>
            </div>
        </div>
    <?php endif; ?>
<?php endforeach; ?>
