<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block Forgotpassword
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var Forgotpassword $block */

use Magento\Customer\Block\Account\Forgotpassword;

?>
<ul class="forgot-password-tab">
    <li class="forgot-password-tab-item active" data-type="email">
        <?= __('Email') ?>
    </li>
    <li class="forgot-password-tab-item" data-type="phone">
        <?= __('Phone') ?>
    </li>
</ul>
<form class="form password forget forget-by-phone"
      action="<?= $block->escapeUrl($block->getUrl('advancedlogin/otp/forgotpasswordpost')) ?>"
      method="post"
      id="form-forgot-password-phone"
      data-mage-init='{"validation":{}}'
      style="display: none">
    <fieldset class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field telephone required">
            <label for="telephone" class="label"><span><?= $block->escapeHtml(__('Telephone')) ?></span></label>
            <div class="control">
                <div class="control-input">
                    <input type="text" name="telephone" alt="telephone" id="telephone" class="input-text"
                           data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'phone-validate': true}">
                </div>
                <button id="sendOtp" class="action primary"><span><?= $block->escapeHtml(__('Send')) ?></span></button>
            </div>
            <div class="otp-message" id="otp-message"></div>
        </div>
        <div class="field email required">
            <label for="otp_code" class="label"><span><?= $block->escapeHtml(__('OTP')) ?></span></label>
            <div class="control">
                <input type="text" data-validate="{required:true}" name="otp_code" alt="otp_code" id="otp_code" class="input-text">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info_phone') ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action submit primary">
                <span><?= $block->escapeHtml(__('Confirm')) ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back"
               href="<?= $block->escapeUrl($block->getLoginUrl()) ?>"><span><?= $block->escapeHtml(__('Cancel')) ?></span></a>
        </div>
    </div>
</form>
<script type="text/x-magento-init">
    {
        "*": {
           "validateMethod": {}
       }
    }

</script>
<script type="text/javascript">
    require(['jquery', 'Magento_Ui/js/modal/alert'], function ($, alert) {
        if(window.location.hash) {
            var hashtag = window.location.hash.substr(1).replace("/","");
            var el = $("ul").find(`[data-type=${hashtag}]`);
            $('.forgot-password-tab-item').removeClass('active');
            el.addClass('active');
            $('.form.password.forget').hide();
            $(`.forget-by-${hashtag}`).show();
        }
        $("#sendOtp").click(function (e) {
            e.preventDefault();
            if($("#telephone").valid()) {
                $.ajax({
                    showLoader: true,
                    url: "<?= $block->getUrl('advancedlogin/otp/sendOtpForgotPassword') ?>",
                    data: {telephone: $("#telephone").val()},
                    type: "POST",
                    success: function (response) {
                        $("#otp-message").html(response.message);
                        $("#sendOtp").prop("disabled",true);
                        var timeLeft = response.remaining;
                        var downloadTimer = setInterval(function(){
                            if(timeLeft <= 0){
                                clearInterval(downloadTimer);
                                document.getElementById("otp-message").innerHTML = "<?= __("You can resend the otp code") ?>";
                                $("#sendOtp").prop("disabled",false);
                            } else {
                                if(document.getElementById("resend-remaining") === null){
                                    clearInterval(downloadTimer);
                                }else{
                                    document.getElementById("resend-remaining").innerHTML = timeLeft;
                                }
                            }
                            timeLeft -= 1;
                        }, 1000);
                    }
                })
            }
        });

        $('.forgot-password-tab-item').on('click', function () {
            let dataType = $(this).attr('data-type');

            $('.forgot-password-tab-item').removeClass('active');
            $(this).addClass('active');
            $('.form.password.forget').hide();
            $(`.forget-by-${dataType}`).show();
            window.location.hash = '#'+dataType;
        })
    })
</script>
