<?php

?>
<?php /** @var $block \Magenest\GoogleTagManager\Block\Gtm */ ?>

<!-- Google Tag Manager -->
<?php // phpcs:ignore MEQP2.Templates.RawJavaScript.FoundRawJS ?>
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'//www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','<?= /** @noEscape */ $block->getAccountId() ?>');</script>
<!-- End Google Tag Manager -->
