<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

use Magento\Framework\Escaper;
use Magento\Framework\View\Helper\SecureHtmlRenderer;
use Magento\Review\Block\Product\View\ListView;

/**
 * @var ListView $block
 * @var SecureHtmlRenderer $secureRenderer
 * @var Escaper $escaper
 */

$_items = $block->getReviewsCollection()->getItems();
$format = $block->getDateFormat() ?: \IntlDateFormatter::SHORT;
?>
<?php if (count($_items)): ?>
    <div class="block review-list" id="customer-reviews">
        <?php if (!$block->getHideTitle()): ?>
            <div class="block-title">
                <strong><?= $escaper->escapeHtml(__('Customer Reviews')) ?></strong>
            </div>
        <?php endif ?>
        <div class="block-content">
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
            <ol class="items review-items">
                <?php foreach ($_items as $_review): ?>
                    <li class="item review-item" itemscope itemprop="review" itemtype="http://schema.org/Review">
                        <div class="review-title">
                            <span class="review-author" itemprop="author">
                                <?= $escaper->escapeHtml($_review->getNickname()) ?>
                            </span>
                            <span class="review-summary" itemprop="name">
                            <?= $escaper->escapeHtml($_review->getTitle()) ?>
                            </span>
                        </div>
                        <div class="review-ratings-wrapper">
                            <?php if (count($_review->getRatingVotes())): ?>
                                <div class="review-ratings">
                                    <?php foreach ($_review->getRatingVotes() as $_vote): ?>
                                        <div class="rating-summary item"
                                             itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                            <span class="label rating-label">
                                                <span><?= $escaper->escapeHtml($_vote->getRatingCode()) ?></span>
                                            </span>
                                            <div class="rating-result"
                                                 id="review_<?= /* @noEscape */ $_review->getReviewId()
                                                    . '_vote_'
                                                    . $_vote->getVoteId() ?>"
                                                 title="<?= $escaper->escapeHtmlAttr($_vote->getPercent()) ?>%">
                                                <meta itemprop="worstRating" content="1"/>
                                                <meta itemprop="bestRating" content="100"/>
                                                <span>
                                                    <span itemprop="ratingValue">
                                                        <?= $escaper->escapeHtml($_vote->getPercent()) ?>%
                                                    </span>
                                                </span>
                                            </div>
                                            <?= /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                                'width:' . $_vote->getPercent() . '%',
                                                'div#review_' . $_review->getReviewId()
                                                . '_vote_' . $_vote->getVoteId() . ' span'
                                            ) ?>
                                        </div>
                                    <?php endforeach; ?>
                                </div>
                            <?php endif; ?>
                            <span class="review-date">
                                <time class="review-details-value" itemprop="datePublished"
                                      datetime="<?= $escaper->escapeHtmlAttr(
                                                        date("M j, Y", strtotime($_review->getCreatedAt()))
                                                    ) ?>">
                                    <?= $escaper->escapeHtmlAttr(
                                                date("M j, Y", strtotime($_review->getCreatedAt()))
                                            )?>
                                </time>
                            </span>
                        </div>
                        <div class="review-content" itemprop="description">
                            <?= /* @noEscape */ nl2br($escaper->escapeHtml($_review->getDetail())) ?>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar">
                <?= $block->getChildHtml('toolbar') ?>
            </div>
        </div>
    </div>
<?php else: ?>
    <div class="block review-list" id="customer-reviews">
        <span><?= __('No reviews yet') ?></span>
    </div>
<?php endif; ?>
