<?php if ($block->isTwitterEnabled()) : ?>
    <div class="modal-socialogin modal-twitter twitter_button_connect">
    </div>
    <?php $scriptString = <<<script
        require(['jquery','magenestSocialLogin'],
            function($,sociallogin){
                $(document).ready(function () {
                    $('.twitter_button_connect').bind('click',function(){
                        var url = '{$block->getButtonUrl()}';
                        if (url.length) {
                            sociallogin.display(url, 'Twitter', 600, 600);
                        }
                    });
                })
            })

script;
    ?>
    <?= isset($secureRenderer) ? $secureRenderer->renderTag('script', [], $scriptString, false) : '<script>' . $scriptString . '</script>' ?>
<?php endif;?>

