<?php if($block->isZaloEnable()) { ?>
    <div class="modal-socialogin modal-zalo zalo_button_connect"></div>
    <?php $scriptString = <<<script
        require(['jquery', 'magenestSocialLogin'],
            function ($, sociallogin) {
                $(document).ready(function () {
                    var btnUrl = "{$block->getButtonUrl()}";
                    $(".zalo_button_connect").bind("click", function () {
                        sociallogin.display(btnUrl, "Zalo", 600, 600);
                    });
                });
            });
script;
    ?>
    <?= isset($secureRenderer) ? $secureRenderer->renderTag('script', [], $scriptString, false) : '<script>' . $scriptString . '</script>' ?>
<?php } ?>
