<?php
// @codingStandardsIgnoreFile
?>
<?php if ($this->isEnabled()) : ?>
    <?php $helper = $this->helper('Acommerce\Gtm\Helper\Data'); ?>
    <?php $quote = $this->getQuote(); ?>
    <?php $products = $this->getProducts(); ?>

    <?php
    $shoppingCartData = [];
    $shoppingCartData['actionField'] = [
        'step' => '0',
        'option' => '' // @TODO Some value can be added
    ];
    $shoppingCartData['basketID'] = $quote->getId();
    $shoppingCartData['basketTotal'] = $helper->numberFormat($quote->getGrandTotal(), 2);
    $shoppingCartData['basketProducts'] = $products;

    $this->setDataLayerOption('event', 'shoppingCart');
    $this->setEcommerceData('shoppingCart', $shoppingCartData);
    ?>
<?php endif; ?>
