<?php

namespace Magenest\AbandonedCart\Model\Coupon;

use Magento\Framework\App\ObjectManager;

class Massgenerator extends \Magento\SalesRule\Model\Coupon\Massgenerator
{

    public function generateAbandonedCartPool($ruleId, $qty, $mailId, $expiredTime, $sendDate)
    {
        $this->generatedCount = 0;
        $this->generatedCodes = [];
        $maxAttempts          = $this->getMaxAttempts() ? $this->getMaxAttempts() : self::MAX_GENERATE_ATTEMPTS;
        $this->increaseLength();
        /** @var $coupon \Magento\SalesRule\Model\Coupon */
        $coupon       = $this->couponFactory->create();
        $nowTimestamp = $this->dateTime->formatDate($sendDate);
        for ($i = 0; $i < $qty; $i++) {
            $attempt = 0;
            do {
                if ($attempt >= $maxAttempts) {
                    throw new \Magento\Framework\Exception\LocalizedException(
                        __('We cannot create the requested Coupon Qty. Please check your settings and try again.')
                    );
                }
                $code = $this->generateCode();
                ++$attempt;
            } while ($this->getResource()->exists($code));
            $expirationDate = new \DateTime($nowTimestamp);
            if (isset($expiredTime['day']) && isset($expiredTime['hour']) && isset($expiredTime['minute'])) {
                $time = 'P';
                $time .= $expiredTime['day'] ? $expiredTime['day'] . 'D' : '';
                $time .= $expiredTime['hour'] || $expiredTime['minute'] ? 'T' : '';
                $time .= $expiredTime['hour'] ? $expiredTime['hour'] . 'H' : '';
                $time .= $expiredTime['minute'] ? $expiredTime['minute'] . 'M' : '';
                if ($expiredTime['day'] || $expiredTime['hour'] || $expiredTime['minute']) {
                    $expirationDate->add(new \DateInterval($time));
                    $expirationDate = $expirationDate->format('Y-m-d H:i:s');
                } else {
                    $expirationDate = null;
                }
            }
            $salesRuleModel = ObjectManager::getInstance()->create(\Magento\SalesRule\Model\Rule::class)->load($ruleId);
            if ($salesRuleModel->getRuleId()) {
                $coupon->setId(null)
                    ->setRuleId($salesRuleModel->getRuleId())
                    ->setUsageLimit($salesRuleModel->getUsesPerCoupon())
                    ->setUsagePerCustomer($salesRuleModel->getUsagePerCustomer())
                    ->setExpirationDate($expirationDate)
                    ->setCreatedAt($nowTimestamp)
                    ->setMailId($mailId)
                    ->setType(\Magento\SalesRule\Helper\Coupon::COUPON_TYPE_SPECIFIC_AUTOGENERATED)
                    ->setCode($code)
                    ->save();
            } else {
                throw new \Exception(__("Rule not exit!"));
            }


            $this->generatedCount   += 1;
            $this->generatedCodes[] = $code;
        }
        return $this->generatedCodes;
    }
}
