<?php
/**
 * @var \Amasty\DeliveryDateManager\Block\Adminhtml\Sales\Order\Create\Deliverydate $block
 * @var \Magento\Framework\Escaper $escaper
 */
?>
<?php if ($block->isEnabledModule()): ?>
    <section class="admin__page-section amasty-deliverydate">
        <div class="admin__page-section-title">
            <span class="title"><?= $escaper->escapeHtml(__('Delivery Information')) ?></span>
        </div>
        <?php foreach ($block->getFormElements() as $element): ?>
            <?= $element->toHtml() ?>
        <?php endforeach; ?>
    </section>
<?php endif; ?>
