<div style="background:#EAF0EE;border:1px solid #CCCCCC;margin-bottom:10px;padding:11px 0 0 10px;">
    <h4>
        <img style="padding-left: 15px;" src="<?php echo $block->getViewFileUrl('Magenest_AdminActivity::images/magenest-logo.png') ?>"/><br><br>
        <div style="padding-left: 15px;">
            <p> <strong style="color:#EA7601;"><?php echo __('Admin Activity (ver.') ?><?php echo $this->getModuleVersion() ?><?php echo __(') - Developed by') ?></strong> <a style="color:#EA7601;" target="_blank" href="#"><strong>Magenest</strong></a></p>
            <p><?php echo __('For technical support ') ?> <a style="color:#EA7601;" href="#" target="_blank"><?php echo __('Contact Us') ?></a> <?php echo __('or email us at') ?> <a style="color:#EA7601;" href="#" target="_blank"><?php echo __('support@magenest.com') ?></a></p>
        </div>
    </h4>
</div>
