<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php $_order = $block->getOrder() ?>
<?php foreach ($_order->getCreditmemosCollection() as $_creditmemo) : ?>
    <div class="order-creditmemo-title">
        <strong><?= $block->escapeHtml(__('Refund #')) ?><?= $block->escapeHtml($_creditmemo->getIncrementId()) ?> </strong>
        <div class="actions">
            <a href="<?= $block->escapeUrl($block->getPrintCreditmemoUrl($_creditmemo)) ?>"
               class="action print"
               target="_blank"
               rel="noopener">
                <span><?= $block->escapeHtml(__('Print Refund')) ?></span>
            </a>
            <a href="<?= $block->escapeUrl($block->getPrintAllCreditmemosUrl($_order)) ?>"
               class="action print-all"
               target="_blank"
               rel="noopener">
                <span><?= $block->escapeHtml(__('Print All Refunds')) ?></span>
            </a>
        </div>
    </div>

    <div class="table-wrapper order-items">
        <table class="data table table-order-items creditmemo" id="my-refund-table-<?= (int) $_creditmemo->getId() ?>">
            <caption class="table-caption"><?= $block->escapeHtml(__('Items Refunded')) ?></caption>
            <thead>
            <tr>
                <th class="col name"><?= $block->escapeHtml(__('Product Name')) ?></th>
                <th class="col sku"><?= $block->escapeHtml(__('SKU')) ?></th>
                <th class="col price"><?= $block->escapeHtml(__('Price')) ?></th>
                <th class="col qty"><?= $block->escapeHtml(__('Qty')) ?></th>
                <th class="col subtotal"><?= $block->escapeHtml(__('Subtotal')) ?></th>
            </tr>
            </thead>
            <?php $_items = $_creditmemo->getAllItems(); ?>
            <?php foreach ($_items as $_item) : ?>
                <?php if (!$_item->getOrderItem()->getParentItem()) : ?>
                    <tbody>
                    <?= $block->getItemHtml($_item) ?>
                    </tbody>
                <?php endif; ?>
            <?php endforeach; ?>
        </table>
        <div class="order-totals">
            <?= $block->getTotalsHtml($_creditmemo) ?>
        </div>
    </div>
    <?= $block->getCommentsHtml($_creditmemo) ?>
<?php endforeach; ?>
