<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login\Info $block */
?>
<?php if ($block->getRegistration()->isAllowed()) : ?>
    <div class="block block-new-customer">
        <div class="block-content" aria-labelledby="block-new-customer-heading">
            <div class="actions-toolbar">
                <div class="secondary">
                    <span><?= __("Don't have an account?") ?></span>
                    <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create secondary"><span><?= $block->escapeHtml(__('Create an Account')) ?></span></a>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>
