<?php
/**
 * Plumrocket Inc.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the End-user License Agreement
 * that is available through the world-wide-web at this URL:
 * http://wiki.plumrocket.net/wiki/EULA
 * If you are unable to obtain it through the world-wide-web, please
 * send an email to support@plumrocket.com so we can send you a copy immediately.
 *
 * @package     Plumrocket Private Sales and Flash Sales v4.x.x
 * @copyright   Copyright (c) 2020 Plumrocket Inc. (http://www.plumrocket.com)
 * @license     http://wiki.plumrocket.net/wiki/EULA  End-user License Agreement
 */

/** @var \Plumrocket\PrivateSale\Block\Event\Product $block */
?>

<?php if ($block->canShowHeader('template_1')): ?>
    <div class="prprivatesale-category-header header-five">
        <div class="prprivatesale-header-content">
            <div class="prprivatesale-header-event-name">
                <?= $block->getEventName() ?>
            </div>
            <div class="prprivatesale-event-timer">
                <?= $this->getChildHtml('privatesale.product.event.timer') ?>
            </div>
        </div>
    </div>
<?php elseif ($block->canShowHeader('template_2')): ?>
    <div class="prprivatesale-category-header product-top-timer">
        <div class="prprivatesale-event-timer">
            <?= $block->getChildHtml('privatesale.product.event.timer') ?>
        </div>
    </div>
<?php endif; ?>
