<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/* @var $block \Magento\Sales\Block\Order\Creditmemo
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$order = $block->getOrder();
?>

<div class="desktop-hide order-id-title">
    <strong><?= __("Order #%1", $order->getIncrementId()) ?></strong>
</div>
<div class="order-details-items creditmemo">
    <?= $block->getChildHtml('creditmemo_items') ?>
</div>

<?php $scriptString = <<<script
    require(['jquery'], function($){
        $('.order-id-title').on('click', function () {
            $(this).next('.order-details-items').slideToggle(300);
            $(this).toggleClass('order-hide');
        })
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
