<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */
/** @var \Magenest\Sales\ViewModel\Order\Recent $viewModel */
$viewModel = $block->getViewModel();
?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
            <tr>
                <th scope="col" class="col id"><?= $block->escapeHtml(__('Order')) ?></th>
                <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                <?= $block->getChildHtml('extra.column.header') ?>
                <th scope="col" class="col address"><?= $block->escapeHtml(__('Address')) ?></th>
                <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                <th scope="col" class="col actions"></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($_orders as $_order) : ?>
                <tr>
                    <td data-th="<?= $block->escapeHtml(__('Order')) ?>" class="col id">
                        #<?= $block->escapeHtml($_order->getRealOrderId()) ?>
                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view desktop-hide">
                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                        </a>
                    </td>
                    <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ date('d/m/Y',strtotime($block->formatDate($_order->getCreatedAt()))) ?></td>
                    <?php $extra = $block->getChildBlock('extra.container'); ?>
                    <?php if ($extra) : ?>
                        <?php $extra->setOrder($_order); ?>
                        <?= $extra->getChildHtml() ?>
                    <?php endif; ?>
                    <td data-th="<?= $block->escapeHtml(__('Address')) ?>" class="col address"><?= $_order->getShippingAddress($_order->getId())->getData('street'). ', '.
                        $_order->getShippingAddress($_order->getId())->getCity(). ', '. $viewModel->getCountryName($_order->getShippingAddress($_order->getId())->getData('country_id')) ?></td>
                    <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status <?= $block->escapeHtml($_order->getStatus()) ?>"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                    <td class="col actions mobile-hide">
                        <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>" class="action view">
                            <span><?= $block->escapeHtml(__('View Order')) ?></span>
                        </a>
                        <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                            <a href="#" data-post='<?= /* @noEscape */
                            $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                ->getPostData($block->getReorderUrl($_order))
                            ?>' class="action order">
                                <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                            </a>
                        <?php endif ?>
                    </td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>
