<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
?>
<?php /** @var  $block \Magento\Sales\Block\Order\View*/
$order = $block->getOrder();
?>
<div class="desktop-hide order-id-title">
    <strong><?= __("Order #%1", $order->getIncrementId()) ?></strong>
</div>
<div class="order-details-items ordered">
    <?php $_order = $block->getOrder() ?>

    <?= $block->getChildHtml('order_items') ?>

    <?php if ($this->helper(\Magento\GiftMessage\Helper\Message::class)->isMessagesAllowed('order', $_order)
        && $_order->getGiftMessageId()
    ) : ?>
        <div class="block block-order-details-gift-message">
            <div class="block-title"><strong><?= $block->escapeHtml(__('Gift Message for This Order')) ?></strong></div>
            <?php
            $_giftMessage = $this->helper(\Magento\GiftMessage\Helper\Message::class)->getGiftMessageForEntity($_order);
            ?>
            <div class="block-content">
                <dl class="item-options">
                    <dt class="item-sender"><strong class="label"><?= $block->escapeHtml(__('From')) ?></strong><?= $block->escapeHtml($_giftMessage->getSender()) ?></dt>
                    <dt class="item-recipient"><strong class="label"><?= $block->escapeHtml(__('To')) ?></strong><?= $block->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                    <dd class="item-message">
                        <?= /* @noEscape */
                        $this->helper(\Magento\GiftMessage\Helper\Message::class)->getEscapedGiftMessage($_order) ?>
                    </dd>
                </dl>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php $scriptString = <<<script
    require(['jquery'], function($){
        $('.order-id-title').on('click', function () {
            $(this).next('.order-details-items').slideToggle(300);
            $(this).toggleClass('order-hide');
        })
    });
script;
?>
<?= /* @noEscape */ $secureRenderer->renderTag('script', [], $scriptString, false); ?>
