<?php
$couponFeedUrl    = $this->getUrl('abandonedcart/rule/couponsearch', ['_current' => false]);
$emailTemplateURL = $this->getUrl('abandonedcart/mail/template', ['_current' => false]);
$uploadAttachUrl  = $this->getUrl('abandonedcart/rule/upload', ['_current' => false]);
?>
<script>
    require([
        "jquery",
        "jquery/ui",
        'Magento_Catalog/catalog/base-image-uploader',
        'mage/validation',
        'prototype',
        "domReady!"
    ], function ($, jqueryui, fileupload, validation) {
        $(document).ready(function () {
            function isUsePromotion() {
                $('.is_use_cart_rule').each(function () {
                    var row_id = $(this).attr('data_name'),
                        tr_id = '.promotion_' + row_id;
                    if ($(this).is(":checked")) {
                        $(tr_id).attr('style', 'display: inherit;');
                        $(this).attr('value', 1);
                    } else {
                        $(tr_id).attr('style', 'display: none;');
                        $(this).attr('value', 0);
                    }
                });
                $('.is_use_cart_rule').on('click', function () {
                    $('.is_use_cart_rule').each(function () {
                        var row_id = $(this).attr('data_name'),
                            tr_id = '.promotion_' + row_id;
                        if ($(this).is(":checked")) {
                            $(tr_id).attr('style', 'display: inherit;');
                            $(this).attr('value', 1);
                        } else {
                            $(tr_id).attr('style', 'display: none;');
                            $(this).attr('value', 0);
                        }
                    });
                });
                $('.is_use_cart_rule_sms').each(function () {
                    var row_id = $(this).attr('data_name'),
                        tr_id = '.promotion_sms_' + row_id;
                    if ($(this).is(":checked")) {
                        $(tr_id).attr('style', 'display: inherit;');
                        $(this).attr('value', 1);
                    } else {
                        $(tr_id).attr('style', 'display: none;');
                        $(this).attr('value', 0);
                    }
                });
                $('.is_use_cart_rule_sms').on('click', function () {
                    $('.is_use_cart_rule_sms').each(function () {
                        var row_id = $(this).attr('data_name'),
                            tr_id = '.promotion_sms_' + row_id;
                        if ($(this).is(":checked")) {
                            $(tr_id).attr('style', 'display: inherit;');
                            $(this).attr('value', 1);
                        } else {
                            $(tr_id).attr('style', 'display: none;');
                            $(this).attr('value', 0);
                        }
                    });
                });
            };
            setInterval(isUsePromotion, 100);
        });
    });
</script>
