<?php
/** @var \Magenest\AbandonedCart\Block\Adminhtml\Rule\Edit\Tab\SMS $block */
?>
<div id="abandonedcart_sms" data-bind="scope:'abandonedcart_sms'">
    <!-- ko template: 'Magenest_AbandonedCart/rule/smsChain' --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "*":{
                "Magento_Ui/js/core/app": <?php /* @escapeNotVerified */
                echo $block->getSMS(); ?>
            }
        }
    
    
    </script>
</div>
