<?php /** @var $block \Amasty\DeliveryDateManager\Block\Sales\Order\Email\Deliverydate */ ?>
<?php /** @var $escaper \Magento\Framework\Escaper */ ?>
<?php $list = $block->getList() ?>
<?php if (!empty($list)): ?>
    <table class="order-details">
        <thead>
        <tr>
            <td class="address-details">
                <h3><?= $escaper->escapeHtml(__('Delivery Date Info:')) ?></h3>
            </td>
        </tr>
        </thead>
        <tbody>
        <?php foreach ($list as $fieldCode => $field): ?>
            <tr>
                <td><label><?= $escaper->escapeHtml($field['label']) ?></label></td>
                <td><?= $escaper->escapeHtml($field['value'], ['br']) ?></td>
            </tr>
        <?php endforeach; ?>
        </tbody>
    </table>
    <br /><br />
<?php endif; ?>
