<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">
        <div class="block-title filter-title">
            <strong><?= $block->escapeHtml(__('Shop By')) ?></strong>
        </div>

        <div class="block-content filter-content">
            <?php if ($block->getChildHtml('state') || $block->getLayer()->getState()->getFilters()) : ?>
            <div class="filter-current-block">
                <strong class="block-subtitle"><?= $block->escapeHtml(__('Current Filter')) ?></strong>
                <?= $block->getChildHtml('state') ?>

                <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                    <div class="block-actions filter-actions">
                        <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Remove all')) ?></span></a>
                    </div>
                <?php endif; ?>
                </div>
            <?php endif; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getRequestVar() == 'cat' && $filter->getItemsCount()) : ?>
                <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                    <?php if ($block->getChildHtml('category.name')): ?>
                        <?= $block->getChildHtml('category.name') ?>
                    <?php else: ?>
                        <span class="category-name"><?= $block->escapeHtml(__($filter->getName())) ?></span>
                    <?php endif; ?>
                </strong>
                <dl class="filter-options" id="narrow-by-list">
                    <dd class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                </dl>
                <?php break;
                endif; ?>
            <?php endforeach; ?>

            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if (!$wrapOptions) : ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Filter By')) ?></strong>
                    <dl class="filter-options" id="narrow-by-list">
                    <?php $wrapOptions = true;
                endif; ?>
                    <?php if (($filter->getRequestVar() != 'cat' && $filter->getItemsCount()) || ($filter->getRequestVar() == 'price')) : ?>
                        <dt role="heading" aria-level="3" class="filter-options-title <?= 'filter-options-title--' . $filter->getRequestVar() ?>"><?= $block->escapeHtml(__($filter->getName())) ?></dt>
                        <dd class="filter-options-content <?= 'filter-options-content--' . $filter->getRequestVar() ?>"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>
                    <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
